services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/www
    networks:
      - inception
    depends_on:
      - wordpress
      - short_urls
      - adminer
    
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress:/www
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env

  redis:
    build: ./requirements/redis
    volumes:
      - redis:/data
    networks:
      - inception

  adminer:
    build: ./requirements/adminer
    networks:
      - inception
    depends_on:
      - mariadb
      - wordpress

  ftp:
    build: ./requirements/ftp
    ports:
      - "20-21:20-21"
      - "30020-30021:30020-30021"
    volumes:
      - wordpress:/home/vsftpd/${FTP_USER}
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env

  short_urls:
    build: ./requirements/short_urls
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env

      
networks:
  inception:

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/pharick/data/mariadb
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: /home/pharick/data/wordpress
      o: bind
      type: none
  redis:
    driver: local
    driver_opts:
      device: /home/pharick/data/redis
      o: bind
      type: none
